import { UserMenuListType } from "@/types/Auth/UserNavMenu";

export const MenuItemsList: UserMenuListType = {
  orders: [
    {
      id: 1,
      name: "أطلب عقارك",
      membershipType: ["property_seeker", "owner", "agent"],
      icon: "/Icons/solar_document-add-outline.svg",
      path: "/order-property",
    },
    {
      id: 2,
      name: "طلبات الفحص والتقييم",
      membershipType: [
        "property_seeker",
        "owner",
        "agent",
        "evaluator",
        "inspector",
        "company_agent",
        "individual_agent",
      ],
      icon: "/Icons/BoxIcons.svg",
      path: "/inspection-and-evaluation-requests",
    },
    {
      id: 3,
      name: "طلب تسويق عقار",
      membershipType: ["property_seeker", "owner", "agent"],
      icon: "/Icons/uit_house-user.svg",
      path: "/real-estate-marketing-request",
    },
    {
      id: 4,
      name: "طلبات المسوق/الوسيط",
      membershipType: ["company_agent", "individual_agent"],
      icon: "/Icons/material-symbols_map-search-outline-rounded.svg",
      path: "/MarketerOrBrokerRequests",
    },
  ],
  advertisements: [
    {
      id: 1,
      name: "إعلان عن عقار",
      membershipType: ["company_agent", "individual_agent", "owner", "agent"],
      icon: "/Icons/fluent_building-32-regular.svg",
      path: "/add-advertisement",
    },
    {
      id: 2,
      name: "إعلاناتي",
      membershipType: ["company_agent", "individual_agent", "owner", "agent"],
      icon: "/Icons/streamline_annoncement-megaphone.svg",
      path: "/my-ads",
    },
  ],
  more: [
    {
      id: 0,
      name: "مزاداتي",
      membershipType: ["auction_companies"],
      icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9IiNkYmRmZTQiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJsdWNpZGUgbHVjaWRlLWhhbW1lci1pY29uIGx1Y2lkZS1oYW1tZXIiPjxwYXRoIGQ9Im0xNSAxMi05LjM3MyA5LjM3M2ExIDEgMCAwIDEtMy4wMDEtM0wxMiA5Ii8+PHBhdGggZD0ibTE4IDE1IDQtNCIvPjxwYXRoIGQ9Im0yMS41IDExLjUtMS45MTQtMS45MTRBMiAyIDAgMCAxIDE5IDguMTcydi0uMzQ0YTIgMiAwIDAgMC0uNTg2LTEuNDE0bC0xLjY1Ny0xLjY1N0E2IDYgMCAwIDAgMTIuNTE2IDNIOWwxLjI0MyAxLjI0M0E2IDYgMCAwIDEgMTIgOC40ODVWMTBsMiAyaDEuMTcyYTIgMiAwIDAgMSAxLjQxNC41ODZMMTguNSAxNC41Ii8+PC9zdmc+",
      path: "/my-auctions",
    },
    {
      id: 1,
      name: "مشاريعي",
      membershipType: ["real_estate_developer", "contracting_company"],
      icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9IiNjN2NkZDUiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBjbGFzcz0ibHVjaWRlIGx1Y2lkZS1mb2xkZXIta2FuYmFuLWljb24gbHVjaWRlLWZvbGRlci1rYW5iYW4iPjxwYXRoIGQ9Ik00IDIwaDE2YTIgMiAwIDAgMCAyLTJWOGEyIDIgMCAwIDAtMi0yaC03LjkzYTIgMiAwIDAgMS0xLjY2LS45bC0uODItMS4yQTIgMiAwIDAgMCA3LjkzIDNINGEyIDIgMCAwIDAtMiAydjEzYzAgMS4xLjkgMiAyIDJaIi8+PHBhdGggZD0iTTggMTB2NCIvPjxwYXRoIGQ9Ik0xMiAxMHYyIi8+PHBhdGggZD0iTTE2IDEwdjYiLz48L3N2Zz4=",
      path: "/my-projects",
    },
    {
      id: 0,
      name: "الملف الشخصي",
      membershipType: [
        "property_seeker",
        "company_agent",
        "inspector",
        "owner",
        "agent",
        "auction_companies",
        "Services Providers",
        "real_estate_developer",
        "contracting_company",
        "individual_agent",
        "engineering_offices",
        "evaluator",
      ],
      icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9IiNhY2I1YzEiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJsdWNpZGUgbHVjaWRlLWNpcmNsZS11c2VyLXJvdW5kLWljb24gbHVjaWRlLWNpcmNsZS11c2VyLXJvdW5kIj48cGF0aCBkPSJNMTggMjBhNiA2IDAgMCAwLTEyIDAiLz48Y2lyY2xlIGN4PSIxMiIgY3k9IjEwIiByPSI0Ii8+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiLz48L3N2Zz4=",
      path: "/profile",
    },
    {
      id: 1,
      name: "المحادثات",
      membershipType: [
        "property_seeker",
        "company_agent",
        "inspector",
        "owner",
        "agent",
        "auction_companies",
        "Services Providers",
        "real_estate_developer",
        "contracting_company",
        "individual_agent",
        "engineering_offices",
        "evaluator",
      ],
      icon: "/Icons/proicons_chat-gray.svg",
      path: "/conversations",
    },
    {
      id: 2,
      name: "المفضلة",
      membershipType: [
        "property_seeker",
        "company_agent",
        "inspector",
        "owner",
        "agent",
        "auction_companies",
        "Services Providers",
        "real_estate_developer",
        "contracting_company",
        "individual_agent",
        "engineering_offices",
        "evaluator",
      ],
      icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9IiNjN2NkZDUiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBjbGFzcz0ibHVjaWRlIGx1Y2lkZS1oZWFydC1pY29uIGx1Y2lkZS1oZWFydCI+PHBhdGggZD0iTTIgOS41YTUuNSA1LjUgMCAwIDEgOS41OTEtMy42NzYuNTYuNTYgMCAwIDAgLjgxOCAwQTUuNDkgNS40OSAwIDAgMSAyMiA5LjVjMCAyLjI5LTEuNSA0LTMgNS41bC01LjQ5MiA1LjMxM2EyIDIgMCAwIDEtMyAuMDE5TDUgMTVjLTEuNS0xLjUtMy0zLjItMy01LjUiLz48L3N2Zz4=",
      path: "/favorites",
    },
    {
      id: 2,
      name: "خدمات الترويج",
      membershipType: [
        "company_agent",
        "owner",
        "agent",

        "individual_agent",
        "engineering_offices",
      ],
      icon: "/Icons/carbon_text-link-analysis.svg",
      path: "/promotion-services",
    },
    // {
    //   id: 3,
    //   name: "حملات التمييز",
    //   membershipType: ["property_seeker", "company_agent", "inspector"],
    //   icon: "/Icons/carbon_text-link-analysis.svg",
    //   path: "/discrimination-campaigns",
    // },
    {
      id: 4,
      name: "الاشتراكات",
      membershipType: [
        "company_agent",
        "owner",
        "agent",

        "individual_agent",
        "engineering_offices",
      ],
      icon: "/Icons/fluent_person-money-20-regular.svg",
      path: "/subscriptions",
    },
    // {
    //   id: 5,
    //   name: "التسجيل كفاحص ومقيم",
    //   membershipType: ["property_seeker", "company_agent", "inspector"],
    //   icon: "/Icons/system-uicons_home-check.svg",
    //   path: "/register-examination-and-evaluation",
    // },
    // {
    //   id: 6,
    //   name: "التسجيل كمكتب هندسي",
    //   membershipType: ["property_seeker", "company_agent", "inspector"],
    //   icon: "/Icons/formkit_add.svg",
    //   path: "/register-engineering-office",
    // },
    // {
    //   id: 7,
    //   name: "التسجيل كمطور عقاري",
    //   membershipType: ["property_seeker", "company_agent", "inspector"],
    //   icon: "/Icons/formkit_add.svg",
    //   path: "/register-developer",
    // },
    // {
    //   id: 8,
    //   name: "التسجيل كشركة مزادات",
    //   membershipType: ["property_seeker", "company_agent", "inspector"],
    //   icon: "/Icons/formkit_add.svg",
    //   path: "/register-auction-company",
    // },
    // {
    //   id: 9,
    //   name: "التسجيل كشركة مقاولات",
    //   membershipType: ["property_seeker", "company_agent", "inspector"],
    //   icon: "/Icons/formkit_add.svg",
    //   path: "/register-contractor-company",
    // },
    {
      id: 10,
      name: "خدمة العملاء",
      membershipType: [
        "property_seeker",
        "company_agent",
        "inspector",
        "owner",
        "agent",
        "auction_companies",
        "Services Providers",
        "real_estate_developer",
        "contracting_company",
        "individual_agent",
        "engineering_offices",
        "evaluator",
      ],
      icon: "/Icons/MessagesCircle.svg",
      path: "/customer-service",
    },
    // {
    //   id: 11,
    //   name: "مشاركة التطبيق",
    //   membershipType: ["property_seeker", "company_agent", "inspector"],
    //   icon: "/Icons/solar_share-outline.svg",
    //   path: "/share-app",
    // },
    {
      id: 12,
      name: "مستندات قانونية",
      membershipType: [
        "property_seeker",
        "company_agent",
        "inspector",
        "owner",
        "agent",
        "auction_companies",
        "Services Providers",
        "real_estate_developer",
        "contracting_company",
        "individual_agent",
        "engineering_offices",
        "evaluator",
      ],
      icon: "/Icons/solar_document-linear.svg",
      subMenu: [
        {
          id: 0,
          name: "الشروط والأحكام",
          membershipType: [
            "property_seeker",
            "company_agent",
            "inspector",
            "owner",
            "agent",
            "auction_companies",
            "Services Providers",
            "real_estate_developer",
            "contracting_company",
            "individual_agent",
            "engineering_offices",
            "evaluator",
          ],
          icon: "/Icons/T&C.svg",
          path: "/terms-and-conditions",
        },
        {
          id: 1,
          name: "سياسة الخصوصية",
          membershipType: [
            "property_seeker",
            "company_agent",
            "inspector",
            "owner",
            "agent",
            "auction_companies",
            "Services Providers",
            "real_estate_developer",
            "contracting_company",
            "individual_agent",
            "engineering_offices",
            "evaluator",
          ],
          icon: "/Icons/T&C.svg",
          path: "/terms-and-conditions#privacyPolicy",
        },
        {
          id: 2,
          name: "سياسة معالجة الشكاوي",
          membershipType: [
            "property_seeker",
            "company_agent",
            "inspector",
            "owner",
            "agent",
            "auction_companies",
            "Services Providers",
            "real_estate_developer",
            "contracting_company",
            "individual_agent",
            "engineering_offices",
            "evaluator",
          ],
          icon: "/Icons/T&C.svg",
          path: "/complaints-handling-mechanism",
        },
        {
          id: 3,
          name: "رخصة فال",
          membershipType: [
            "property_seeker",
            "company_agent",
            "inspector",
            "owner",
            "agent",
            "auction_companies",
            "Services Providers",
            "real_estate_developer",
            "contracting_company",
            "individual_agent",
            "engineering_offices",
            "evaluator",
          ],
          icon: "/Icons/Fal License.svg",
          onClick: true,
        },
        {
          id: 4,
          name: "شهادة ضريبة القيمة المضافة",
          membershipType: [
            "property_seeker",
            "company_agent",
            "inspector",
            "owner",
            "agent",
            "auction_companies",
            "Services Providers",
            "real_estate_developer",
            "contracting_company",
            "individual_agent",
            "engineering_offices",
            "evaluator",
          ],
          icon: "/Icons/VAT.svg",
          onClick: true,
        },
      ],
    },
    {
      id: 13,
      name: "عن عقرها",
      membershipType: [
        "property_seeker",
        "company_agent",
        "inspector",
        "owner",
        "agent",
        "auction_companies",
        "Services Providers",
        "real_estate_developer",
        "contracting_company",
        "individual_agent",
        "engineering_offices",
        "evaluator",
        "property_seeker",
        "company_agent",
        "inspector",
      ],
      icon: "/Icons/mdi_about-circle-outline.svg",
      path: "/aboutUs",
    },
    {
      id: 14,
      name: "الإعدادات",
      membershipType: [
        "property_seeker",
        "company_agent",
        "inspector",
        "owner",
        "agent",
        "auction_companies",
        "Services Providers",
        "real_estate_developer",
        "contracting_company",
        "individual_agent",
        "engineering_offices",
        "evaluator",
      ],
      icon: "/Icons/Setting.svg",
      subMenu: [
        // {
        //   id: 1,
        //   name: "العربية",
        //   membershipType: ["property_seeker", "company_agent", "inspector"],
        //   icon: "/Icons/globe.svg",
        //   path: "/language",
        // },
        // {
        //   id: 2,
        //   name: "تعديل تفاصيل شركة المقاولات",
        //   membershipType: ["property_seeker", "company_agent", "inspector"],
        //   icon: "/Icons/solar_document-add-outline.svg",
        //   path: "/edit-company",
        // },
        {
          id: 3,
          name: "تغيير كلمة المرور",
          membershipType: [
            "property_seeker",
            "company_agent",
            "inspector",
            "owner",
            "agent",
            "auction_companies",
            "Services Providers",
            "real_estate_developer",
            "contracting_company",
            "individual_agent",
            "engineering_offices",
            "evaluator",
          ],
          icon: "/Icons/Lock.svg",
          path: "/profile",
        },
        {
          id: 4,
          name: "تغيير رقم الجوال",
          membershipType: [
            "property_seeker",
            "company_agent",
            "inspector",
            "owner",
            "agent",
            "auction_companies",
            "Services Providers",
            "real_estate_developer",
            "contracting_company",
            "individual_agent",
            "engineering_offices",
            "evaluator",
          ],
          icon: "/Icons/ph_phone-light.svg",
          path: "/profile",
        },
      ],
    },
  ],
};
