import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "@/styles/globals.css";
import Header from "../components/layout/Header";
import StoreProvider from "@/providers/StoreProvider";
import Footer from "../components/layout/Footer";
import ScrollUp from "../components/layout/scrollUp";
import { Toaster } from "../components/ui/sonner";
import ChatBotBtn from "@/components/atoms/buttons/ChatBotBtn";

const RubikSans = Rubik({
  variable: "--font-Rubik-sans",
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "عقرها",
  description: "Generated by create next app",
  icons: { icon: "/Logo/Aqerha Icon.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body className={`${RubikSans.variable} antialiased`}>
        <StoreProvider>
          <Header />
          {children}
          <ScrollUp />
          <ChatBotBtn />
          <Footer />
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
