import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/layout/Header";
import StoreProvider from "@/providers/StoreProvider";
import Footer from "@/components/layout/Footer";
import ScrollUp from "@/components/layout/scrollUp";

const RubikSans = Rubik({
  variable: "--font-Rubik-sans",
  subsets: ["arabic"],
  weight: ["300", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${RubikSans.variable} antialiased`}>
        <StoreProvider>
          <Header />
          {children}
          <ScrollUp />
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
