import { AuctionType } from "@/types/Actions";

export const AuctionsList: AuctionType[] = [
  {
    id: 1,
    name: "مزاد روائع الرياض",
    image: "/Images/Link → p16-516x360.jpg.jpg",
    location: "الصناعية الثانية, الدمام",
    NumAssets: 2,
    StartedIn: "2 مارس 2025",
    ExpiresIn: "21 س - 43 د",
    ElapsedTime: "2 يوم 3ساعات",
    StartPrice: 20000,
    EndPrice: 73000,
    NumAuctions: 4,
    stateTime: "جاري الآن",
    place: "إلكتروني",
    stateAction: "شارك بالمزاد الآن",
  },
  {
    id: 2,
    name: "مزاد روائع الرياض",
    image: "/Images/Link → p16-516x360.jpg.jpg",
    location: "الصناعية الثانية, الدمام",
    NumAssets: 2,
    StartedIn: "2 مارس 2025",
    ExpiresIn: "21 س - 43 د",
    ElapsedTime: "2 يوم 3ساعات",
    StartPrice: 20000,
    EndPrice: 73000,
    NumAuctions: 2,
    stateTime: "جاري الآن",
    place: "إلكتروني",
    stateAction: "التسجيل مفتوح",
  },
  {
    id: 3,
    name: "مزاد روائع الرياض",
    image: "/Images/Link → p16-516x360.jpg.jpg",
    location: "الصناعية الثانية, الدمام",
    NumAssets: 2,
    StartedIn: "2 مارس 2025",
    ExpiresIn: "21 س - 43 د",
    ElapsedTime: "2 يوم 3ساعات",
    StartPrice: 20000,
    EndPrice: 73000,
    NumAuctions: 0,
    stateTime: "قادم",
    place: "إلكتروني",
    stateAction: "التسجيل مفتوح",
  },
  {
    id: 4,
    name: "مزاد روائع الرياض",
    image: "/Images/Link → p16-516x360.jpg.jpg",
    location: "الصناعية الثانية, الدمام",
    NumAssets: 2,
    StartedIn: "2 مارس 2025",
    ExpiresIn: "21 س - 43 د",
    ElapsedTime: "2 يوم 3ساعات",
    StartPrice: 20000,
    EndPrice: 73000,
    NumAuctions: 2,
    stateTime: "قادم",
    place: "إلكتروني",
    stateAction: "التسجيل مفتوح",
  },
];
