import { MarketerOrBrokerRequestType } from "@/types/marketerOrBroker";

export const MarketerOrBrokerRequestList: MarketerOrBrokerRequestType[] = [
  {
    id: 1,
    name: "مطلوب فيلا للبيع فى حي المروة, جدة",
    category: "أرض",
    minAria: 250,
    maxAria: 500,
    minPrice: 2000000,
    maxPrice: 5000000,
    phone: "",
    whatsapp: "",
  },
  {
    id: 2,
    name: "مطلوب فيلا للبيع فى حي المروة, جدة",
    category: "شقق",
    minAria: 250,
    maxAria: 500,
    minPrice: 2000000,
    maxPrice: 5000000,
    phone: "",
    whatsapp: "",
  },
  {
    id: 3,
    name: "مطلوب فيلا للبيع فى حي المروة, جدة",
    category: "فيلا",
    minAria: 250,
    maxAria: 500,
    minPrice: 2000000,
    maxPrice: 5000000,
    phone: "",
    whatsapp: "",
  },
  {
    id: 4,
    name: "مطلوب فيلا للبيع فى حي المروة, جدة",
    category: "عمارة",
    minAria: 250,
    maxAria: 500,
    minPrice: 2000000,
    maxPrice: 5000000,
    phone: "",
    whatsapp: "",
  },
];
