import { OptionType } from "@/types/selects";

export const cities: OptionType[] = [
  { label: "الرياض", value: "الرياض" },
  { label: "جدة", value: "جدة" },
  { label: "مكة المكرمة", value: "مكة المكرمة" },
  { label: "المدينة المنورة", value: "المدينة المنورة" },
  { label: "الدمام", value: "الدمام" },
  { label: "الخبر", value: "الخبر" },
  { label: "الطائف", value: "الطائف" },
  { label: "القطيف", value: "القطيف" },
  { label: "الهفوف", value: "الهفوف" },
  { label: "المبرز", value: "المبرز" },
  { label: "تبوك", value: "تبوك" },
  { label: "حائل", value: "حائل" },
  { label: "بريدة", value: "بريدة" },
  { label: "عنيزة", value: "عنيزة" },
  { label: "خميس مشيط", value: "خميس مشيط" },
  { label: "أبها", value: "أبها" },
  { label: "نجران", value: "نجران" },
  { label: "جازان", value: "جازان" },
  { label: "ينبع", value: "ينبع" },
  { label: "رابغ", value: "رابغ" },
  { label: "الجبيل", value: "الجبيل" },
  { label: "الخرج", value: "الخرج" },
  { label: "بيشة", value: "بيشة" },
  { label: "القريات", value: "القريات" },
  { label: "عرعر", value: "عرعر" },
  { label: "سكاكا", value: "سكاكا" },
  { label: "الدوادمي", value: "الدوادمي" },
  { label: "الزلفي", value: "الزلفي" },
  { label: "الرس", value: "الرس" },
  { label: "البكيرية", value: "البكيرية" },
  { label: "الشنان", value: "الشنان" },
  { label: "البدائع", value: "البدائع" },
  { label: "الليث", value: "الليث" },
  { label: "محايل عسير", value: "محايل عسير" },
  { label: "المجاردة", value: "المجاردة" },
  { label: "ظهران الجنوب", value: "ظهران الجنوب" },
  { label: "بلجرشي", value: "بلجرشي" },
  { label: "الباحة", value: "الباحة" },
  { label: "المخواة", value: "المخواة" },
  { label: "الوجه", value: "الوجه" },
  { label: "ضباء", value: "ضباء" },
  { label: "حقل", value: "حقل" },
  { label: "أملج", value: "أملج" },
  { label: "بدر", value: "بدر" },
  { label: "العيص", value: "العيص" },
  { label: "العلا", value: "العلا" },
  { label: "خيبر", value: "خيبر" },
  { label: "تيماء", value: "تيماء" },
  { label: "النعيرية", value: "النعيرية" },
  { label: "حفر الباطن", value: "حفر الباطن" },
  { label: "رأس تنورة", value: "رأس تنورة" },
  { label: "قرية العليا", value: "قرية العليا" },
  { label: "سراة عبيدة", value: "سراة عبيدة" },
  { label: "رجال ألمع", value: "رجال ألمع" },
  { label: "شرورة", value: "شرورة" },
  { label: "سبت العلاية", value: "سبت العلاية" },
  { label: "تثليث", value: "تثليث" },
  { label: "النماص", value: "النماص" },
  { label: "ثادق", value: "ثادق" },
  { label: "حريملاء", value: "حريملاء" },
  { label: "مرات", value: "مرات" },
  { label: "المجمعة", value: "المجمعة" },
  { label: "شقراء", value: "شقراء" },
  { label: "الغاط", value: "الغاط" },
  { label: "حوطة بني تميم", value: "حوطة بني تميم" },
  { label: "الحريق", value: "الحريق" },
  { label: "السليل", value: "السليل" },
  { label: "وادي الدواسر", value: "وادي الدواسر" },
  { label: "الخرمة", value: "الخرمة" },
  { label: "رنية", value: "رنية" },
  { label: "تربة", value: "تربة" },
  { label: "القنفذة", value: "القنفذة" },
  { label: "المظيلف", value: "المظيلف" },
  { label: "العرضيات", value: "العرضيات" },
  { label: "المويه", value: "المويه" },
  { label: "ميسان", value: "ميسان" },
  { label: "الرين", value: "الرين" },
];

export const CitiesTabItems = [
  { value: "", label: "الكل" },
  { value: "الطائف", label: "الطائف" },
  { value: "الخبر", label: "الخبر" },
  { value: "الدمام", label: "الدمام" },
  { value: "المدينة المنورة", label: "المدينة المنورة" },
  { value: "مكة", label: "مكة" },
  { value: "جدة", label: "جدة" },
  { value: "الرياض", label: "الرياض" },
];
